using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Bgfx.Net.Generator.Tests")]

namespace Bgfx.Net.Generator;

/// <summary>
/// Orchestrates the pipeline of <see cref="CSharpSyntaxRewriter"/> passes that
/// transform upstream's <c>bgfx.raw.cs</c> into the wrapper's <c>bgfx.g.cs</c>.
/// Each pass is a single-purpose rewriter in the <c>Rewriters/</c> folder; this
/// type just composes them in the order they must run.
/// </summary>
internal static class BindingRewriter
{
    public static string Rewrite(string source)
    {
        var tree = CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Latest));
        var root = (CompilationUnitSyntax)tree.GetRoot();

        root = (CompilationUnitSyntax)new NamespaceRewriter().Visit(root)!;
        root = (CompilationUnitSyntax)new ClassNameRewriter().Visit(root)!;
        root = (CompilationUnitSyntax)new NestedTypeHoistRewriter().Visit(root)!;
        root = (CompilationUnitSyntax)new MethodNameRewriter().Visit(root)!;
        root = (CompilationUnitSyntax)new LibraryImportRewriter().Visit(root)!;
        root = (CompilationUnitSyntax)new StructFieldPascalCaseRewriter().Visit(root)!;
        root = (CompilationUnitSyntax)new HandleStructRewriter().Visit(root)!;
        root = EnsureUsings(root);
        root = AddHeaderComment(root);

        return root.ToFullString();
    }

    private static CompilationUnitSyntax EnsureUsings(CompilationUnitSyntax root)
    {
        // CallConvCdecl lives in System.Runtime.CompilerServices and is referenced
        // by the per-method [UnmanagedCallConv] attribute LibraryImportRewriter emits.
        var required = new[] { "System.Runtime.CompilerServices" };
        var existing = new HashSet<string>(
            root.Usings.Select(u => u.Name?.ToString() ?? string.Empty),
            StringComparer.Ordinal);

        foreach (var name in required)
        {
            if (existing.Add(name))
            {
                var parsed = (UsingDirectiveSyntax)SyntaxFactory.ParseCompilationUnit($"using {name};\n").Usings[0];
                root = root.AddUsings(parsed);
            }
        }
        return root;
    }

    private static CompilationUnitSyntax AddHeaderComment(CompilationUnitSyntax root)
    {
        var header = SyntaxFactory.ParseLeadingTrivia(
            """
            // <auto-generated>
            //   This file was produced by Bgfx.Net.Generator from bgfx.raw.cs.
            //   DO NOT EDIT. Re-run build/run-generator.ps1 after a submodule bump.
            // </auto-generated>


            """);
        return root.WithLeadingTrivia(header.AddRange(root.GetLeadingTrivia()));
    }
}
